#!/bin/bash

clear

banner="\033[1;31m
    ____             __  ______      __       
   / __ )____ ______/ /_/_  __/_  __/ /_  ___ 
  / __  / __  / ___/ __ \/ / / / / / __ \/ _ \ 
 / /_/ / /_/ (__  ) / / / / / /_/ / /_/ /  __/ 
/_____/\__,_/____/_/ /_/_/  \__,_/_.___/\___/ 
                                              
\033[1;34m
  [[	Coded By: MD. Tonmoy Islam	]]
    [[    Github ID: tonmoy-islam     ]]
      [[       Version: 1.0	    ]]
	≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈
\033[1;32mChoose Video Quality:
(1) Low (360p)
(2) Medium (480p)
(3) High (bigger than 480p)
"
echo -e "$banner"
echo ""
echo -e -n "\033[1;33mInput Quality: "
read qlt
echo -e -n "\033[1;33mPlease give the video url: "
read usr

if [ $qlt = '' ]
then
bashtube
elif [ $qlt = '1' ]
then
youtube-dl -f 'bestvideo[height<=360]+bestaudio/best[height<=360]' $usr
elif [ $qlt = '2' ]
then
youtube-dl -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' $usr
elif [ $qlt = '3' ]
then
youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' $usr
else
echo -e "\033[1;31mWrong Input"
sleep 0.5s
bashtube
fi

if [ $usr == "" ]
then
bashtube
fi
